### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Skyline23** [TotallyMehis/StandUp#1]
X:\Server\cstrike\addons\sourcemod\scripting\standup_core.sp<614>:error 100: function prototypes do not match
X:\Server\cstrike\addons\sourcemod\scripting\standup_core.sp<615>:error 100: function prototypes do not match
X:\Server\cstrike\addons\sourcemod\scripting\standup_core.sp<2873>:error 100: function prototypes do not match
X:\Server\cstrike\addons\sourcemod\scripting\standup_core.sp<2874>:error 100: function prototypes do not match

**Comment by TotallyMehis** [comment]
You forgot to download the standup_core folder. (path: scripting/standup_core/)
To properly compile all plugins, you need to have the include files and in some cases you need a folder which is called the same as the plugin. (eg, scripting/standup_core.sp and scripting/standup_core/)

To put it shortly, if you have no idea what you're doing, just paste the entire scripting folder and drag and drop the plugins onto compile.exe (compiled smx plugin goes to ./plugins/ folder) or spcomp.exe

**Comment by Skyline23** [comment]
I have standup_core folder..

**Comment by TotallyMehis** [comment]
I just downloaded the zip file and used latest stable SM version to compile standup_core and got no errors. Try downloading it again and using latest SM version.

**Comment by Skyline23** [comment]
Thanks.Now I can compile standup_core.
